# Generated by Django 3.2.18 on 2024-04-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('circlename', models.CharField(db_column='CircleName', max_length=50)),
                ('regionname', models.CharField(db_column='RegionName', max_length=50)),
                ('divisionname', models.CharField(db_column='DivisionName', max_length=50)),
                ('officename', models.CharField(db_column='OfficeName', max_length=50)),
                ('pincode', models.CharField(db_column='Pincode', max_length=50)),
                ('officetype', models.CharField(db_column='OfficeType', max_length=50)),
                ('delivery', models.CharField(db_column='Delivery', max_length=50)),
                ('district', models.CharField(db_column='District', max_length=50)),
                ('statename', models.CharField(db_column='StateName', max_length=50)),
                ('latitude', models.CharField(db_column='Latitude', max_length=50)),
                ('longitude', models.CharField(db_column='Longitude', max_length=50)),
            ],
            options={
                'db_table': 'pincode_table',
            },
        ),
    ]
